name: Frontend CI

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    test-build-client:
        name: Build Client Portal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
                  cache-dependency-path: casebridge-client/package-lock.json
            - name: Install dependencies
              run: npm ci
              working-directory: casebridge-client
            - name: Build
              run: npm run build
              working-directory: casebridge-client

    test-build-internal:
        name: Build Internal Portal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
                  cache-dependency-path: CaseBridge_Internal/package-lock.json
            - name: Install dependencies
              run: npm ci
              working-directory: CaseBridge_Internal
            - name: Build
              run: npm run build
              working-directory: CaseBridge_Internal
